apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: rl-arena
type: kubernetes.io/dockerconfigjson
data:
  # Base64로 인코딩된 Docker 레지스트리 인증 정보
  # 생성 방법:
  # kubectl create secret docker-registry registry-credentials \
  #   --docker-server=<REGISTRY_URL> \
  #   --docker-username=<USERNAME> \
  #   --docker-password=<PASSWORD> \
  #   --docker-email=<EMAIL> \
  #   --namespace=rl-arena
  #
  # 예시 (Docker Hub):
  # kubectl create secret docker-registry registry-credentials \
  #   --docker-server=https://index.docker.io/v1/ \
  #   --docker-username=myusername \
  #   --docker-password=mypassword \
  #   --docker-email=myemail@example.com \
  #   --namespace=rl-arena
  #
  # 또는 기존 .docker/config.json 사용:
  # kubectl create secret generic registry-credentials \
  #   --from-file=.dockerconfigjson=$HOME/.docker/config.json \
  #   --type=kubernetes.io/dockerconfigjson \
  #   --namespace=rl-arena
  .dockerconfigjson: e30K  # 임시 빈 값 (실제 환경에서 교체 필요)
